/* ============================================================
   TurNet — ortak veri: tedarikçiler, kategoriler, lokasyonlar
   ============================================================ */

const CATEGORY_LABELS = {
  otel: { tr: "Otel", en: "Hotel" },
  acente: { tr: "Seyahat Acentesi", en: "Travel Agency" },
  rehber: { tr: "Tur Rehberi", en: "Tour Guide" },
  firma: { tr: "Tur Firması", en: "Tour Company" },
};

const CATEGORIES = [
  { key: "otel",   plural: { tr: "Oteller", en: "Hotels" },        count: "1.240",
    desc: { tr: "Şehir otellerinden resortlara, acentelere özel kontenjan ve komisyonlu çalışma.", en: "From city hotels to resorts — agency allotments and commission models." } },
  { key: "acente", plural: { tr: "Acenteler", en: "Agencies" },     count: "860",
    desc: { tr: "Incoming, MICE ve paket tur uzmanı, belgeli seyahat acenteleri.", en: "Licensed agencies specialized in incoming, MICE and package tours." } },
  { key: "rehber", plural: { tr: "Tur Rehberleri", en: "Tour Guides" }, count: "2.100",
    desc: { tr: "TUREB ruhsatlı, çok dilli profesyonel turist rehberleri.", en: "Licensed, multilingual professional tourist guides." } },
  { key: "firma",  plural: { tr: "Tur Firmaları", en: "Tour Companies" }, count: "540",
    desc: { tr: "Balon, yat, günlük tur ve aktivite operatörleri.", en: "Balloon, yacht, daily tour and activity operators." } },
];

const LISTINGS = [
  // ---- OTELLER ----
  { id: 1,  cat: "otel", name: "Kaya Palas Hotel", country: "Türkiye", city: "Antalya", district: "Muratpaşa", coords: [36.885, 30.705],
    desc: "Denize sıfır, 240 odalı 5 yıldızlı şehir oteli. Acentelere özel kontenjan ve komisyonlu çalışma modeli.",
    about: "1998'den bu yana Antalya Muratpaşa'da hizmet veren Kaya Palas, 240 oda ve 3 restoranıyla hem bireysel hem grup konaklamalarına ev sahipliği yapar. Acenteler için sezonluk kontenjan, seri rezervasyon indirimi ve esnek iptal koşulları sunar.",
    services: ["Konaklama", "Toplantı salonu", "Transfer", "Grup indirimi", "Yarım pansiyon"],
    rating: 4.8, reviews: 132, tag: "5 Yıldız", verified: true, featured: 10, response: "~4 sa", member: "2023" },
  { id: 2,  cat: "otel", name: "Taş Konak Cappadocia", country: "Türkiye", city: "Nevşehir", district: "Ürgüp", coords: [38.630, 34.910],
    desc: "Restore edilmiş kaya oteli, 28 butik oda. Balon turu paketleriyle kombine B2B fiyatlandırma.",
    about: "Ürgüp'ün tarihi taş konaklarından dönüştürülen otel, 28 özel tasarım odasıyla üst segment misafirlere hitap eder. Balon ve atölye turlarıyla kombine paketlerde acente komisyonu uygulanır.",
    services: ["Konaklama", "Kahvaltı dahil", "Balon paketi", "Özel transfer"],
    rating: 4.9, reviews: 98, tag: "Butik", verified: true, featured: 9, response: "~3 sa", member: "2024" },
  { id: 3,  cat: "otel", name: "Marmara Liman Otel", country: "Türkiye", city: "İstanbul", district: "Beyoğlu", coords: [41.032, 28.977],
    desc: "Galata bölgesinde 76 odalı şehir oteli. Grup konaklamalarında esnek iptal koşulları.",
    about: "Galata Kulesi'ne yürüme mesafesinde, 76 odalı şehir oteli. Kruvaziyer grupları ve kültür turu operatörleriyle uzun dönemli kontenjan anlaşmaları yapılır.",
    services: ["Konaklama", "Grup indirimi", "Erken giriş", "Bagaj odası"],
    rating: 4.5, reviews: 210, tag: "Şehir Oteli", verified: false, featured: 6, response: "~8 sa", member: "2024" },
  { id: 4,  cat: "otel", name: "Ege Bay Resort", country: "Türkiye", city: "Muğla", district: "Bodrum", coords: [37.034, 27.430],
    desc: "Her şey dahil konseptli 380 odalı resort. Yurt dışı acenteler için charter kontenjanı mevcut.",
    about: "Bodrum yarımadasında 380 odalı, her şey dahil resort. Yurt dışı tur operatörleri için charter kontenjanı, yurt içi acenteler için erken rezervasyon dönem fiyatları sunulur.",
    services: ["Her şey dahil", "Aquapark", "Toplantı salonu", "Transfer", "Animasyon"],
    rating: 4.6, reviews: 301, tag: "Resort", verified: true, featured: 8, response: "~6 sa", member: "2023" },
  { id: 5,  cat: "otel", name: "Santorini Blue Suites", country: "Yunanistan", city: "Santorini", district: "Oia", coords: [36.461, 25.375],
    desc: "Caldera manzaralı 18 süit. Türk acentelerle TL bazlı sözleşme imkânı, balayı segmenti odaklı.",
    about: "Oia'nın caldera hattında 18 süitlik butik tesis. Türk acentelerle TL bazlı sözleşme yapılabilir; balayı ve mini grup segmentine özel paketler mevcuttur.",
    services: ["Konaklama", "Balayı paketi", "Özel havuz", "Transfer"],
    rating: 4.9, reviews: 87, tag: "Butik", verified: true, featured: 7, response: "~12 sa", member: "2025" },

  // ---- ACENTELER ----
  { id: 6,  cat: "acente", name: "Anadolu Tur & Travel", country: "Türkiye", city: "İstanbul", district: "Kadıköy", coords: [40.990, 29.030],
    desc: "A grubu işletme belgeli incoming acentesi. Kültür turları ve MICE organizasyonlarında 15 yıllık deneyim.",
    about: "2009'da kurulan A grubu acente; incoming kültür turları, kongre ve teşvik organizasyonlarında uzman. Avrupa ve Uzak Doğu pazarlarından yıllık 40 binin üzerinde misafir ağırlar.",
    services: ["Incoming", "MICE", "Kültür turu", "Vize danışmanlığı", "Ulaşım"],
    rating: 4.7, reviews: 64, tag: "A Grubu", verified: true, featured: 10, response: "~2 sa", member: "2023" },
  { id: 7,  cat: "acente", name: "Likya Travel", country: "Türkiye", city: "Antalya", district: "Kaş", coords: [36.200, 29.640],
    desc: "Batı Akdeniz odaklı butik acente. Yat kiralama, mavi yolculuk ve dalış paketlerinde B2B iş birliği.",
    about: "Kaş merkezli butik acente; mavi yolculuk, dalış ve doğa turlarında bölgenin yerel uzmanı. Diğer acentelere komisyonlu paket ve ortak kontenjan modeli sunar.",
    services: ["Mavi yolculuk", "Dalış", "Yat kiralama", "Doğa turları"],
    rating: 4.8, reviews: 45, tag: "Butik", verified: true, featured: 8, response: "~5 sa", member: "2024" },
  { id: 8,  cat: "acente", name: "Doğu Ekspres Turizm", country: "Türkiye", city: "İzmir", district: "Konak", coords: [38.420, 27.130],
    desc: "Yurt içi paket turlar ve okul gezilerinde uzman acente. Acenteler arası kontenjan paylaşımına açık.",
    about: "İzmir merkezli acente; yurt içi paket turlar, okul ve kurumsal geziler düzenler. Acenteler arası kontenjan paylaşımı ve ortak kalkış modeliyle çalışır.",
    services: ["Paket tur", "Okul gezisi", "Kurumsal gezi", "Ulaşım"],
    rating: 4.4, reviews: 89, tag: "Yurt İçi", verified: false, featured: 5, response: "~10 sa", member: "2025" },
  { id: 9,  cat: "acente", name: "Batum Gateway DMC", country: "Gürcistan", city: "Batum", district: "Merkez", coords: [41.640, 41.640],
    desc: "Gürcistan'da yerel DMC. Türk acenteler için Batum–Tiflis kombine programları ve transfer ağı.",
    about: "Batum merkezli destinasyon yönetim şirketi. Türk acenteler için Batum–Tiflis kombine programları, kongre organizasyonu ve ülke geneli transfer ağı sağlar.",
    services: ["DMC", "Transfer ağı", "Kombine program", "Kongre"],
    rating: 4.6, reviews: 38, tag: "DMC", verified: true, featured: 7, response: "~6 sa", member: "2024" },

  // ---- REHBERLER ----
  { id: 10, cat: "rehber", name: "Elif Demirkan", country: "Türkiye", city: "İstanbul", district: "Fatih", coords: [41.013, 28.950],
    desc: "TUREB ruhsatlı profesyonel rehber. İngilizce & İspanyolca, tarihi yarımada ve müze turlarında uzman.",
    about: "12 yıllık TUREB ruhsatlı rehber; İngilizce ve İspanyolca dillerinde tarihi yarımada, Topkapı ve Ayasofya turlarında uzman. Kruvaziyer ve incoming gruplarla düzenli çalışır.",
    services: ["İngilizce", "İspanyolca", "Müze turu", "Kruvaziyer grubu"],
    rating: 5.0, reviews: 156, tag: "EN · ES", verified: true, featured: 10, response: "~1 sa", member: "2023" },
  { id: 11, cat: "rehber", name: "Mehmet Aksoy", country: "Türkiye", city: "Nevşehir", district: "Avanos", coords: [38.715, 34.850],
    desc: "Kapadokya bölge rehberi. Almanca grup turları, atölye ziyaretleri ve özel trekking rotaları.",
    about: "Kapadokya'da yaşayan bölge rehberi; Almanca konuşan gruplara vadi yürüyüşleri, çömlek atölyeleri ve özel rotalar düzenler.",
    services: ["Almanca", "Trekking", "Atölye turu", "Özel rota"],
    rating: 4.9, reviews: 121, tag: "DE", verified: true, featured: 9, response: "~2 sa", member: "2024" },
  { id: 12, cat: "rehber", name: "Ayşe Yıldız", country: "Türkiye", city: "İzmir", district: "Selçuk", coords: [37.950, 27.370],
    desc: "Efes ve çevresi arkeoloji turlarında 12 yıllık deneyim. Fransızca ve İngilizce kruvaziyer grupları.",
    about: "Efes, Meryem Ana ve Şirince hattında arkeoloji ağırlıklı turlar; Fransızca ve İngilizce. Kuşadası limanına gelen kruvaziyer gruplarında deneyimli.",
    services: ["Fransızca", "İngilizce", "Arkeoloji", "Kruvaziyer grubu"],
    rating: 4.8, reviews: 203, tag: "FR · EN", verified: true, featured: 8, response: "~3 sa", member: "2023" },
  { id: 13, cat: "rehber", name: "Kerem Ulusoy", country: "Türkiye", city: "Muğla", district: "Fethiye", coords: [36.650, 29.120],
    desc: "Likya Yolu ve doğa turları rehberi. Rusça konuşan gruplar için tekne ve yamaç paraşütü programları.",
    about: "Fethiye merkezli doğa ve macera rehberi; Likya Yolu etapları, tekne günleri ve yamaç paraşütü programlarında Rusça konuşan gruplarla çalışır.",
    services: ["Rusça", "Likya Yolu", "Tekne turu", "Macera"],
    rating: 4.7, reviews: 77, tag: "RU", verified: false, featured: 6, response: "~7 sa", member: "2025" },

  // ---- TUR FİRMALARI ----
  { id: 14, cat: "firma", name: "Göktürk Balloons", country: "Türkiye", city: "Nevşehir", district: "Göreme", coords: [38.643, 34.830],
    desc: "Sivil havacılık lisanslı balon işletmesi. Acentelere sezonluk blok satış ve komisyon modeli.",
    about: "SHGM lisanslı balon işletmesi; 12 balonluk filo ile günde 240 misafir kapasitesi. Acentelere sezonluk blok satış, son dakika kontenjanı ve kademeli komisyon sunar.",
    services: ["Balon turu", "Blok satış", "Otel transferi", "Video çekim"],
    rating: 4.9, reviews: 412, tag: "Balon Turu", verified: true, featured: 10, response: "~2 sa", member: "2023" },
  { id: 15, cat: "firma", name: "Mavi Yol Yachting", country: "Türkiye", city: "Muğla", district: "Marmaris", coords: [36.850, 28.270],
    desc: "12 guletlik filoyla mavi yolculuk operasyonu. Haftalık kiralama ve kabin satışında B2B fiyat listesi.",
    about: "Marmaris çıkışlı 12 guletlik filo; haftalık özel kiralama ve kabin bazlı satış. Acentelere sezon başında net B2B fiyat listesi ve kontenjan garantisi verilir.",
    services: ["Gulet kiralama", "Kabin satışı", "Mavi yolculuk", "İkram"],
    rating: 4.8, reviews: 96, tag: "Gulet", verified: true, featured: 9, response: "~4 sa", member: "2024" },
  { id: 16, cat: "firma", name: "Pamukkale Adventures", country: "Türkiye", city: "Denizli", district: "Pamukkale", coords: [37.920, 29.120],
    desc: "Yamaç paraşütü ve antik kent kombine turları. Günlük operasyon, acente paneli üzerinden anlık kontenjan.",
    about: "Pamukkale'de yamaç paraşütü ve Hierapolis kombine günlük turları. Acente paneli üzerinden anlık kontenjan görüntüleme ve rezervasyon imkânı.",
    services: ["Yamaç paraşütü", "Antik kent", "Günlük tur", "Sigorta dahil"],
    rating: 4.6, reviews: 154, tag: "Macera", verified: true, featured: 7, response: "~5 sa", member: "2024" },
  { id: 17, cat: "firma", name: "Bosphorus Line Cruises", country: "Türkiye", city: "İstanbul", district: "Beşiktaş", coords: [41.043, 29.007],
    desc: "Boğaz teknesi ve davet organizasyonları. Kurumsal etkinlik ve incoming gruplara özel kapasite.",
    about: "Boğaz'da 3 tekneyle gezi ve davet organizasyonları. Incoming acenteler ve kurumsal etkinlik planlayıcıları için özel kiralama ve sabit sefer kontenjanı.",
    services: ["Tekne turu", "Davet", "Kurumsal etkinlik", "İkram"],
    rating: 4.5, reviews: 188, tag: "Tekne Turu", verified: false, featured: 6, response: "~9 sa", member: "2025" },
  { id: 18, cat: "firma", name: "Tbilisi Old Town Tours", country: "Gürcistan", city: "Tiflis", district: "Mtatsminda", coords: [41.715, 44.800],
    desc: "Tiflis şehir turları ve şarap rotaları operatörü. Türkçe rehberli programlar, acente komisyonu %15.",
    about: "Tiflis eski şehir turları ve Kakheti şarap rotaları. Türkçe rehberli programlar; Türk acentelere %15 standart komisyon ve ortak pazarlama desteği.",
    services: ["Şehir turu", "Şarap rotası", "Türkçe rehber", "Transfer"],
    rating: 4.7, reviews: 52, tag: "Şehir Turu", verified: true, featured: 7, response: "~6 sa", member: "2024" },
];

/* ---------------- yardımcılar ---------------- */
function getListing(id) { return LISTINGS.find((l) => l.id === Number(id)); }
function uniqSorted(arr) { return [...new Set(arr)].sort((a, b) => a.localeCompare(b, "tr")); }
