-- İşletme/üye oturum olayları — giriş, çıkış, başarısız giriş.
-- audit_logs yalnızca admin işlemleri içindir; üye tarafı buraya yazılır.
-- Hacmi düşük, değeri yüksek: "hesabıma girilmiş" iddiasının tek kaynağı.
-- Migration idempotenttir.

create table if not exists public.session_events (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users(id) on delete set null,
  -- Kullanıcı silinse bile olay kaydı anlamlı kalsın diye e-posta denormalize edilir.
  email      text,
  event      text not null,
  -- Serbest metin ayrıntı: 'manual' | 'invite-accept' | 'expired' | hata kodu…
  reason     text,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now(),
  constraint session_events_event_check
    check (event in ('login', 'logout', 'login_failed', 'mfa_failed')),
  constraint session_events_reason_len check (reason is null or char_length(reason) <= 200),
  constraint session_events_email_len  check (email  is null or char_length(email)  <= 200)
);

create index if not exists session_events_user_idx
  on public.session_events (user_id, created_at desc);
create index if not exists session_events_created_idx
  on public.session_events (created_at desc);
-- Brute-force taraması: aynı e-postaya art arda başarısız giriş.
create index if not exists session_events_failed_idx
  on public.session_events (email, created_at desc)
  where event = 'login_failed';

-- Immutable: yazıldıktan sonra değiştirilemez/silinemez (retention job hariç, aşağıda).
create or replace function public.prevent_session_event_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'session_events immutable; update/delete is not allowed';
end;
$$;

drop trigger if exists session_events_no_update on public.session_events;
create trigger session_events_no_update
  before update on public.session_events
  for each row execute function public.prevent_session_event_mutation();

alter table public.session_events enable row level security;

-- Yazım yalnızca service-role üzerinden (uygulama sunucusu). Policy tanımlanmadığı
-- için authenticated/anon hiçbir şey yazamaz veya okuyamaz.
drop policy if exists "session events admin read" on public.session_events;
create policy "session events admin read" on public.session_events
  for select using (public.is_admin());

comment on table public.session_events is
  'Uye oturum olaylari (login/logout/login_failed). Yalnizca service-role yazar, admin okur.';
