-- İşletmelerin DB'de yaptığı değişikliklerin izi — kim, ne zaman, hangi satırda,
-- hangi alanı neyle değiştirdi.
--
-- Neden trigger, neden uygulama kodu değil: writeAdminAudit() elle çağrılıyor ve
-- yalnızca admin action'larını kapsıyor; panel (işletme sahibi), cron, service-role
-- ve SQL Editor'den yapılan yazımlar kapsam dışı kalıyordu. Trigger hangi yoldan
-- gelirse gelsin yakalar.
--
-- Saklama politikası: yalnızca DEĞİŞEN alanların eski/yeni değeri tutulur (tam satır
-- kopyası değil) — tablo boyutu birkaç kat küçülür ve gereksiz kişisel veri
-- kopyalanmaz. Süre sonunda 0003 no'lu retention job temizler.
-- Migration idempotenttir.

create table if not exists public.record_changes (
  id             bigint generated by default as identity primary key,
  table_name     text not null,
  record_id      text not null,
  -- İşletme bazlı geçmişi tek indeksle çekebilmek için denormalize edilir.
  business_id    bigint,
  op             text not null check (op in ('INSERT', 'UPDATE', 'DELETE')),
  actor_id       uuid,
  -- 'authenticated' | 'service_role' | 'postgres' (cron) | 'anon'
  actor_role     text,
  changed_fields text[] not null default '{}',
  old_value      jsonb,
  new_value      jsonb,
  created_at     timestamptz not null default now()
);

create index if not exists record_changes_record_idx
  on public.record_changes (table_name, record_id, created_at desc);
create index if not exists record_changes_business_idx
  on public.record_changes (business_id, created_at desc)
  where business_id is not null;
create index if not exists record_changes_actor_idx
  on public.record_changes (actor_id, created_at desc);
create index if not exists record_changes_created_idx
  on public.record_changes (created_at desc);

-- Immutable (retention job'ın delete'i hariç).
create or replace function public.prevent_record_change_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'record_changes immutable; update is not allowed';
end;
$$;

drop trigger if exists record_changes_no_update on public.record_changes;
create trigger record_changes_no_update
  before update on public.record_changes
  for each row execute function public.prevent_record_change_mutation();

alter table public.record_changes enable row level security;

drop policy if exists "record changes admin read" on public.record_changes;
create policy "record changes admin read" on public.record_changes
  for select using (public.is_admin());

-- İşletme sahibi kendi işletmesinin değişiklik geçmişini görebilir.
drop policy if exists "record changes owner read" on public.record_changes;
create policy "record changes owner read" on public.record_changes
  for select using (
    business_id is not null
    and exists (
      select 1 from public.businesses b
      where b.id = record_changes.business_id and b.owner_id = auth.uid()
    )
  );

-- ============================================================
-- Aktör çözümü
-- RLS istemcisinde auth.uid() doludur. Service-role istemcisinde (createAdminClient)
-- JWT'de sub yoktur; o yollarda uygulama isterse set_config('app.actor_id', …, true)
-- ile gerçek kullanıcıyı geçebilir, geçmezse actor_id null kalır ve actor_role
-- 'service_role' olarak görünür.
-- ============================================================
create or replace function public.current_actor_id()
returns uuid
language plpgsql
stable
as $$
declare
  raw text;
begin
  raw := nullif(current_setting('app.actor_id', true), '');
  if raw is null then
    raw := nullif(current_setting('request.jwt.claim.sub', true), '');
  end if;
  if raw is null then
    begin
      raw := nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub';
    exception when others then
      raw := null;
    end;
  end if;
  return nullif(raw, '')::uuid;
exception when others then
  return null;
end;
$$;

-- ============================================================
-- Generic satır değişikliği logger'ı
-- ============================================================
create or replace function public.log_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  o          jsonb := case when tg_op = 'INSERT' then '{}'::jsonb else to_jsonb(old) end;
  n          jsonb := case when tg_op = 'DELETE' then '{}'::jsonb else to_jsonb(new) end;
  changed    text[];
  old_slim   jsonb := '{}'::jsonb;
  new_slim   jsonb := '{}'::jsonb;
  k          text;
  biz        bigint;
  -- Gürültü: otomatik/teknik alanlar. Denetim değeri yok, log'u şişirir.
  -- rating/reviews yorum trigger'ından, email_* alanları gönderim cron'undan güncellenir.
  noise      text[] := array['updated_at', 'search_vector', 'rating', 'reviews',
                             'email_status', 'email_sent_at', 'provider_message_id',
                             'last_error'];
  -- Asla loglanmayacak alanlar (sır / kimlik doğrulama materyali).
  secrets    text[] := array['password', 'password_hash', 'token', 'access_token',
                             'refresh_token', 'secret', 'api_key', 'otp', 'code_hash'];
begin
  o := o - noise - secrets;
  n := n - noise - secrets;

  -- Değişen alanlar: iki yönlü fark (silinen anahtarlar da yakalanır).
  select coalesce(array_agg(distinct key order by key), '{}')
    into changed
    from (
      select key from jsonb_object_keys(o) key
      union
      select key from jsonb_object_keys(n) key
    ) keys
   where (o -> key) is distinct from (n -> key);

  -- Alan değişmemişse (ör. yalnızca updated_at dokunmuş) kayıt açma.
  if cardinality(changed) = 0 then
    return null;
  end if;

  -- Yalnızca değişen alanların eski/yeni değeri saklanır.
  foreach k in array changed loop
    if o ? k then old_slim := old_slim || jsonb_build_object(k, o -> k); end if;
    if n ? k then new_slim := new_slim || jsonb_build_object(k, n -> k); end if;
  end loop;

  -- İşletme bağlamı: businesses tablosunda id, alt tablolarda business_id.
  if tg_table_name = 'businesses' then
    biz := nullif(coalesce(n ->> 'id', o ->> 'id'), '')::bigint;
  else
    biz := nullif(coalesce(n ->> 'business_id', o ->> 'business_id'), '')::bigint;
  end if;

  insert into public.record_changes (
    table_name, record_id, business_id, op, actor_id, actor_role,
    changed_fields, old_value, new_value
  )
  values (
    tg_table_name,
    coalesce(n ->> 'id', o ->> 'id', ''),
    biz,
    tg_op,
    public.current_actor_id(),
    coalesce(nullif(current_setting('request.jwt.claim.role', true), ''), current_user),
    changed,
    case when tg_op = 'INSERT' then null else old_slim end,
    case when tg_op = 'DELETE' then null else new_slim end
  );

  return null;
exception when others then
  -- Log yazımı asıl işlemi ASLA düşürmemeli.
  raise warning 'log_row_change failed on %: %', tg_table_name, sqlerrm;
  return null;
end;
$$;

comment on function public.log_row_change() is
  'Generic satir degisikligi logger''i; yalnizca degisen alanlari record_changes''e yazar.';

-- ============================================================
-- Trigger'ların takılması
-- Kapsam dışı bırakılanlar (bilinçli): page_views, rate_limits, *_deliveries,
-- signup_intents, business_drafts, audit_logs, record_changes, session_events —
-- yüksek hacimli ya da zaten log niteliğinde.
-- ============================================================
do $$
declare
  t text;
  audited text[] := array[
    'businesses',
    'business_contacts',
    'business_services',
    'business_memberships',
    'business_partners',
    'business_partner_requests',
    'profiles',
    'quotes',
    'quote_responses'
  ];
begin
  foreach t in array audited loop
    if to_regclass('public.' || t) is null then
      raise notice 'tablo yok, atlaniyor: %', t;
      continue;
    end if;
    execute format('drop trigger if exists %I on public.%I', t || '_row_audit', t);
    execute format(
      'create trigger %I after insert or update or delete on public.%I
         for each row execute function public.log_row_change()',
      t || '_row_audit', t
    );
  end loop;
end;
$$;
